### ISSUE TITLE
Debugging does not work

### ISSUE THREAD

**Issue by mitar** [ruby-rdf/json-ld#37]
It seems `--dbg` does not work?

```
$ jsonld --dbg in.json 
/Users/user/.gem/ruby/2.4.0/gems/json-ld-2.1.3/bin/jsonld:133:in `block in <top (required)>': undefined method `debug=' for JSON::LD:Module (NoMethodError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/getoptlong.rb:605:in `block in each'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/getoptlong.rb:602:in `loop'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/getoptlong.rb:602:in `each'
	from /Users/user/.gem/ruby/2.4.0/gems/json-ld-2.1.3/bin/jsonld:131:in `<top (required)>'
	from /Users/user/.gem/ruby/2.4.0/bin/jsonld:22:in `load'
	from /Users/user/.gem/ruby/2.4.0/bin/jsonld:22:in `<main>'
```

**Comment by gkellogg** [comment]
This command is mostly used for internal purposes, there's actually an `rdf` command that provides access to these features that is somewhat more robust.

There is a new way to get to this information other than the `debug=` interface, which I'll update.

**Comment by gkellogg** [comment]
Note that most debug calls have been commented out for performance purposes, but you'll get some useful output, particularly when framing.
